sudo: required 
language: cpp
dist: xenial
compiler: 
    - clang
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - clang++-7.0
            - valgrind
install:
    - "[ $CXX = clang++ ] && export CXX=clang++-7.0 || true"
# Install conan
    - pip install conan --user
# Automatic detection of arch, compiler, etc.
    - conan user
    - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
# Need to manually install aquila
    - git clone https://github.com/zsiciarz/aquila.git aquila-src
    - mkdir aquila-build && pushd aquila-build
    - cmake ../aquila-src
    - make
    - sudo make install
    - popd
script:
# Download dependencies 
    - mkdir .conan && pushd .conan && conan install .. -s compiler=clang -s compiler.version=7.0 -s compiler.libcxx=libstdc++11 --build=missing && popd
# Build Project
    - mkdir cmake-build && cd cmake-build
    - cmake .. -G "Unix Makefiles"
    - make
# Run your tests
